steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - pocket-manager
      - --region=asia-northeast1
      - --source=.
      - --trigger-topic=pocket-manager
      - --entry-point=Run
      - --runtime=go121
      - --max-instances=1
      - --set-env-vars=POCKET_CONSUMER_KEY=${_POCKET_CONSUMER_KEY},POCKET_ACCESS_TOKEN=${_POCKET_ACCESS_TOKEN},SLACK_POST_URL=${_SLACK_POST_URL}
